services:

  postgres:
    image: postgres:15
    container_name: subscriptions_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscriptions
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: subscriptions_app
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env

volumes:
  postgres_data: